name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
        matrix:
          version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.version }}
          push: true
          platforms: 'amd64,arm64'
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.version }}-${{ github.sha }}
